### ISSUE TITLE
apple notary errors

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-utility-build-application#1]
Hi Miyako,

fantastic job from, you. But there are a few errors
build with macOS 10.14.5
4Dv17r5 from today   

all options on:
$path:="Develop:EXPOSE_Build:Final Application:EXPOSE.app"

$versionID:="1002"

$signApp:=True
$signNativeComponents:=True
$signHelper:=True

  //these are not necessary (signed with .app, presumably)
$signFrameworks:=True
$signInternalComponents:=True

$signPlugins:=True
$signSASLPlugins:=True
$signPHP:=True
$signHelpers:=True
-------------

   "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/MacOS/EXPOSE",
      "message": "The signature of the binary is invalid.",
      "docUrl": null,
      "architecture": "x86_64"

      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libEGL.dylib",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
     "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libEGL.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
    "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libGLESv2.dylib",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
     "severity": "error",
      "code": null,

      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libGLESv2.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libswiftshader_libEGL.dylib",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libswiftshader_libEGL.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libswiftshader_libGLESv2.dylib",
      "message": "The binary is not signed.",
      "docUrl": null,
      "architecture": "x86_64"
      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libswiftshader_libGLESv2.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"

And I get also errors for some of the plugins:
**Window Button**
      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Plugins/Window Button.bundle/Contents/MacOS/Window Button",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "i386"

**Ghostscript:**
   "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Plugins/GS.bundle/Contents/MacOS/GS",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "i386"
    },
    {
      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Plugins/GS.bundle/Contents/MacOS/GS",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Plugins/GS.bundle/Contents/MacOS/libgs.9.21.dylib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "i386"
    },
    {
      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Plugins/GS.bundle/Contents/MacOS/libgs.9.21.dylib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"

**Common Crypto:**
      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Plugins/Common Crypto.bundle/Contents/MacOS/Common Crypto",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "i386"
    },
    {
      "severity": "error",
      "code": null,
      "path": "EXPOSE.dmg/EXPOSE.app/Contents/Plugins/Common Crypto.bundle/Contents/MacOS/Common Crypto",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"

Armin

**Comment by miyako** [comment]
I've created a blog post to keep track of plugins that need to be updated 

https://miyako.github.io/2019/06/21/update-sdk.html

nowadays I try to use static libraries as much as possible, 
but for something like GhostScript, dylib seems to be only option.

so I need to update the library too, which takes time (cause I build for 32-bit and 64-bit using different SDK and lipo

**Comment by miyako** [comment]
I've updated the plugins, and added code to sign InstallTool.app and the CEF dylibs,
but I can't help you with PHP.
sorry for that.

**Comment by miyako** [comment]
I also see "invalid destination for symbolic link in bundle" for CEF.

c.f.

https://developer.apple.com/library/archive/technotes/tn2206/_index.html

until I solve this, I will not push the update for component

**Comment by miyako** [comment]
comparing 17R5 to 17.2, it seems odd that 4D Helper.app should have a frameworks folder inside it.

**Comment by miyako** [comment]
I've adapted the component for 17R5

**Comment by ArminDeeg** [comment]
Great Miyako,

the list is now shorter than before. (**compiled app with integrated 4d volume desktop v17r5**)


severity | "error"
-- | --
code | null
path | "EXPOSE.dmg/EXPOSE.app/Contents/Resources/Updater/Updater.app/Contents/Frameworks/libxerces-c_3_2.dylib"
message | "The binary is not signed."
docUrl | null
architecture | "x86_64"
10 |  
severity | "error"
code | null
path | "EXPOSE.dmg/EXPOSE.app/Contents/Resources/Updater/Updater.app/Contents/Frameworks/libxerces-c_3_2.dylib"
message | "The signature does not include a secure timestamp."
docUrl | null
architecture | "x86_64"
11 |  
severity | "error"
code | null
path | "EXPOSE.dmg/EXPOSE.app/Contents/Resources/Updater/Updater.app/Contents/MacOS/Updater"
message | "The binary is not signed."
docUrl | null
architecture | "x86_64"
12 |  
severity | "error"
code | null
path | "EXPOSE.dmg/EXPOSE.app/Contents/Resources/Updater/Updater.app/Contents/MacOS/Updater"
message | "The signature does not include a secure timestamp."
docUrl | null
architecture | "x86_64"
13 |  
severity | "error"
code | null
path | "EXPOSE.dmg/EXPOSE.app/Contents/Resources/Updater/Updater.app/Contents/MacOS/Updater"
message | "The executable does not have the hardened runtime enabled."
docUrl | null
architecture | "x86_64"


I use your default settings:

$signApp:=True
$signNativeComponents:=True

  //these are not necessary (signed with .app, presumably)
**$signFrameworks:=False
$signInternalComponents:=False**

$signPlugins:=True
$signSASLPlugins:=True
$signPHP:=True
$signHelpers:=True

**Comment by miyako** [comment]
for the Updater I have added a new $signUpdater flag

**Comment by miyako** [comment]
I've downgraded libgs, just in case. not thoroughly tested.

**Comment by miyako** [comment]
can we close this issue?

GS is recompiled https://github.com/miyako/4d-plugin-gs/releases

and Updater is discussed in #2
