### ISSUE TITLE
Problem with the installer .dmg created with this utility (mac Os Catalina)

### ISSUE THREAD

**Issue by AlfonsoIdem** [miyako/4d-utility-build-application#11]
Hi Miyako.

Working with v18 R2 (OEM)

I have create the DMG for installation of myApp Stand Alone, with this utility. 
I upload to my website system for customers download .

I go into a client's computer (with mac Os Catalina) and download it from my Web site https:// .
Then copy to the Applications folder (I've also tried ii on desktop and documents folders).

I start MyApp and the system ask me for rights. I give rights.

But after a while I get the message: Would you open the Structure on Read Only mode?

If I get information in the installed folder and files, they are Read & Write for everyone.

I hope it is clear now.

You can see in attached image
![rw](https://user-images.githubusercontent.com/48951166/77246160-bf295180-6c24-11ea-909f-ca71f279c909.jpg)

**Comment by miyako** [comment]
it sounds like your app is translocated.

it means that the code signature is invalid.

you should verify if your app signature is valid

```sh
codesign --verify --verbose (path}
```

and id notarisation is valid

```
spctl --assess --verbose --type exec
```

**Comment by AlfonsoIdem** [comment]
Each time I send to apple for notarize I've receive an email form apple : Your Mac software was successfully notarized.

So, I supposed all was right.

I did check with codesign --verify --verbose (path} every ".app" and it was also right 
and also with spctl --assess --verbose --type exec {path}.

So, aldo I supposed all was right.

But I've made now with .dmg and I get not signed at all ¿?¿?

The structure I have for create the .dmg is

A folder ("install folder") thas have all my files and folders to install:   myApp folder, Application alias, read me alias 
![install](https://user-images.githubusercontent.com/48951166/77294922-55bd4780-6ce5-11ea-9cbe-6ae12c167705.jpg)

myApp folder contain : myApp.app (signed), Data folder (not signed), read me files (not signed)
![install2](https://user-images.githubusercontent.com/48951166/77294936-5c4bbf00-6ce5-11ea-84d1-2571d4f2fee3.jpg)

In your utility in hdiutil first parameter i put "install folder"

I thought it was right. Isn't it?

**Comment by miyako** [comment]
to be clear, the tool does the following:

1. codesign the app
2. create an archive of the app (dmg, pkg or zip)
3. send it to Apple notary service.

Apple notarisation applies to the exact .dmg that you send in step 2.
in your screenshots, you have some other files inside the .dmg.
is this the .dmg that you sent in step 2?
if not, step 1 to 3 has no relations to the .dmg you distribute.

you must notarise the exact .dmg you send to Apple.

also, every content inside that .dmg must be signed.

**Comment by AlfonsoIdem** [comment]
The path I use for .dmg in the tool, is the folder ( first screenshot) that contain alias and the IdemCONTA folder with the IdemCONTA.app and other files .txt, .rtf, .4dd, ... (not signed).

**Comment by AlfonsoIdem** [comment]
After the step 1 I copy the codesigned app to this path, for creation of the .dmg

**Comment by miyako** [comment]
I did not consider complex dmg for this tool. if could find a way to do it via CLI

https://cutecoder.org/programming/notarize-disk-image-developer-id-distribution/

and report here how it can be done, I can incorporate the process in the tool.

**Comment by miyako** [comment]
not 100% sure, but perhaps the problem is that you don't sign the dmg.

maybe it's not a problem if only the app is inside, and the app is signed.

**Comment by AlfonsoIdem** [comment]
This link has clarify my problem.
It has more work for a dmg with folder.
I have to create the dmg from my install folder. I have made manually.
there is an example for automated:
create-dmg \
--background ../window-background@2x.png \
--volname "Your App Name" \
--window-pos 200 120 \
--window-size 800 400 \
--icon-size 100 \
--icon "YourAppName.app" 200 190 \
--hide-extension "YourAppName.app" \
--app-drop-link 600 185 \
~/Downloads/AppPackage.dmg \
"StagingDir/"

After that, I have to sign the created .dmg
xcrun codesign --force --sign "Developer ID Application: YourIdentity" AppPackage.dmg

Then Norarize.

And also recomend to Staple the dmg

xcrun stapler staple AppPackage.dmg

Which in case of no Internet will let open the dmg

Will be great if you can add to the installer option.
I will try by my own.

Now it works.
Thank you! very much.
