### ISSUE TITLE
Notarization issues with 4Dv18 R3 and macOS 10.15.6

### ISSUE THREAD

**Issue by abachler** [miyako/4d-utility-build-application#13]
I’ve been successfully notarizing apps builded with 4D v18R2 since a few of months.

We are now using 4D v18R3 (macOS 10.15.6) and notarization is failing.
I don’t know if the failure is due to 4D v18R3 or to some changes on macOS.

This is what Apple Notarization log is reporting:

“issues”: [
{
“severity”: “error”,
“code”: null,
“path”: “SchoolTrack_12.6_Server.dmg/SchoolTrack 12.6 Server.app/Contents/MacOS/SchoolTrack 12.6”,
“message”: “The signature of the binary is invalid.”,
“docUrl”: null,
“architecture”: “x86_64”
},
{
“severity”: “error”,
“code”: null,
“path”: “SchoolTrack_12.6_Server.dmg/SchoolTrack 12.6 Server.app/Contents/Native Components/WebViewerCEF.bundle/Contents/MacOS/WebViewerCEF”,
“message”: “The signature of the binary is invalid.”,
“docUrl”: null,
“architecture”: “x86_64”
},
{
“severity”: “error”,
“code”: null,
“path”: “SchoolTrack_12.6_Server.dmg/SchoolTrack 12.6 Server.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/4D Helper (Plugin).app/Contents/MacOS/4D Helper (Plugin)”,
“message”: “The signature of the binary is invalid.”,
“docUrl”: null,
“architecture”: “x86_64”
},
{
“severity”: “error”,
“code”: null,
“path”: “SchoolTrack_12.6_Server.dmg/SchoolTrack 12.6 Server.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/4D Helper (GPU).app/Contents/MacOS/4D Helper (GPU)”,
“message”: “The signature of the binary is invalid.”,
“docUrl”: null,
“architecture”: “x86_64”
},
{
“severity”: “error”,
“code”: null,
“path”: “SchoolTrack_12.6_Server.dmg/SchoolTrack 12.6 Server.app/Contents/Native Components/WebViewerCEF.bundle/Contents/Frameworks/4D Helper (Renderer).app/Contents/MacOS/4D Helper (Renderer)”,
“message”: “The signature of the binary is invalid.”,
“docUrl”: null,
“architecture”: “x86_64”
}
]

**Comment by miyako** [comment]
well, I just ran the code on 10.15.6, 18 R3, on a built app as well as 4D itself.

both cases, notarisation success.

are you sure the code is up-to-date? how many lines in the method "TEST" ? answer:428

**Comment by abachler** [comment]
Miyako,

Thanks for your answer and the tests.
Yes, I haven’t touched your code at all in my last test (I downloaded again the BUILD database), is 428 lines.

I tested notarizing 4D Server itself and it worked too…
I’m lost. I would recheck everything and come back to you.

Alberto

**Comment by miyako** [comment]
Sometimes codesign leaves residue (.cstemp files) that invalidates codesigning.

Simply re-building and re-signing might fix it.
