### ISSUE TITLE
Server Database arm64 notarization

### ISSUE THREAD

**Issue by PhilippeGanter** [miyako/4d-utility-build-application#15]
Using 3/8/21 build with arm64 support
Applying the tool to a signed v19 built server, its built client and built single user (3 apps)
Single user and Client app OK
Server returns this:
```
      "path": "ViniMaster_F_Server.dmg/ViniMaster_F Server.app/Contents/Server Database/Libraries/lib4d-arm64.dylib",
      "message": "The binary is not signed with a valid Developer ID certificate.",

      "path": "ViniMaster_F_Server.dmg/ViniMaster_F Server.app/Contents/Server Database/Libraries/lib4d-arm64.dylib",
      "message": "The signature does not include a secure timestamp.",
```

Looks like Server Database is not processed for arm64 notarization. What should I change/set?

Or is it a 4D build issue?

Thanks in advance
Phil

**Comment by miyako** [comment]
if you trace the code you'd see that the *$signDatabase*  option does not look into *Server Database*.

I've added and pushed the needed changes but I don't have time to test it

**Comment by PhilippeGanter** [comment]
It works, thank you.
