### ISSUE TITLE
Catalina Notarization

### ISSUE THREAD

**Issue by scopie2** [miyako/4d-utility-build-application#3]
I used your 4d-utility-build-application on my app and it notarized and stapled without issue. (For my app, line 88 in TEST needs to have "resources" substituted for "libraries" to avoid a 'no such path' error on line 89)

The app starts up without problems on Mojave with the 'Apple found no malware' text in the Open dialog. Thank you. 

On the latest Catalina public beta, however, there is no malware text in the Open dialog and the app crashes.

Is this Apple's issue, 4D's issue or does your utility need further work for Catalina? I understand it's probably not worth any effort on your part until the shipping version of Catalina is released.

**Comment by miyako** [comment]
to clarify whether it is a notarisation issue or a compatibility issue,
could you please launch a standard (not built) version of 4D on Catalina and see what happens?

**Comment by scopie2** [comment]
When I double click 4D 17.2 on on my machine running Catalina public beta (whole folder containing everything needed to run the interpreted app sent over by air drop), I get the message: "4D can't be opened because Apple cannot check it for malicious software". So I can't try running the interpreted app. I get the same message when I double click on my app's structure file — for some reason Catalina tries to open the structure file with 4D server as first choice.

I will leave it to you to interpret this.

**Comment by miyako** [comment]
macOS Launch Services decides which app to open your 4DB file. If 4D Server is the latest app registered (by moving to /Applications) then it may be its first choice. if 17.2 is not compatible with Catelina to begin with, notarisation will not solve your issue.

**Comment by ArminDeeg** [comment]
The bug fix List mentioned that you need 17.2hf1 for Catalina

**Comment by scopie2** [comment]
Thanks. I will wait for 17.3 as a beta will not work for my use case.
