### ISSUE TITLE
extract signed and notarized app from dmg ?

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-utility-build-application#5]
Hi Miyako,

do you have sample code how to extract the signed and notarized 4d.app from the dmg to the prevoius location ?
We like to integrate the notarized app into an own installer ?
I cannot find the extract option inside the hdiutil manual.

Or is it better to use your second option with ditto an use your zip plugin to extract the app ?

Thanks Armin

**Comment by miyako** [comment]
there is no concept of "extracting" an app out of the ``.dmg`` you submitted to the notary server.

basically you  call ``hdiutil`` twice. 

once, you call it to create the ``.dmg`` you send to the notary service via ``altool``.
after that, you call ``xcrun stapler staple`` on the app to staple the notary ticket to the app,
then you create another ``.dmg`` with ``hdiutil``.

**Comment by ArminDeeg** [comment]
Thanks Miyako,

2 more questions.

1. The LEP with xcrun stapler staple PATHTOAPP works without the ticket ID ?
2. Can I use this command after receiving the ticked ID or do I have to wait for the Apple notarization success confirmation ?

Armin

**Comment by miyako** [comment]
``xcrun stapler`` internally calls CloudKit to connect to iTunes.
that is why you need to use it after notarization has succeeded.
https://developer.apple.com/documentation/xcode/notarizing_your_app_before_distribution/customizing_the_notarization_workflow?language=objc
