### ISSUE TITLE
some notarizing warnings

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-utility-build-application#6]
Build with latest v17r6 beta on macOS 10.13.6 
latest 4d-utility-build-application

[https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma113/v4/a9/2c/2b/a92c2b94-e384-8ee7-9d64-5927bb21569c/developer_log.json?accessKey=1571598785_1967464153845019211_VX%2BDy5HUQd3GkTXt30H0JpCy3IUVD7KW4A7OOKwqvUDHz8XnoXPjAqt3n%2BDZjzCHTl%2BKSpxwmCoMUYwsKMdl13CjRHlqfPmRu0RQBvovfPSQt7TBWoZn0tx0NbUtZ5ySgvQ%2FXlFjfRR%2FvsCRSsy0p1d%2FmLd%2FZFcmcW8n%2BXCTyLY%3D]

  |  
-- | --
logFormatVersion | 1
jobId | "174e6734-6930-4bc9-8976-73711fccf188"
status | "Accepted"
statusSummary | "Ready for distribution"
statusCode | 0
archiveFilename | "EXPOSE.zip"
uploadDate | "2019-10-18T13:07:35Z"
sha256 | "c9da43bd28759038561f00dacc191e24c8c1df5f35797cfa192d005ad728538d"

issues |  
-- | --
0 |  
severity | "warning"
code | null
path | "EXPOSE.zip/EXPOSE.app/Contents/MacOS/EXPOSE"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "x86_64"
1 |  
severity | "warning"
code | null
path | "EXPOSE.zip/EXPOSE.app/Contents/MacOS/EXPOSE"
message | "The signature algorithm used is too weak."
docUrl | null
architecture | "x86_64"
2 |  
severity | "warning"
code | null
path | "EXPOSE.zip/EXPOSE.app/Contents/MacOS/EXPOSE"
message | "The signature does not include a secure timestamp."
docUrl | null
architecture | "x86_64"
3 |  
severity | "warning"
code | null
path | "EXPOSE.zip/EXPOSE.app/Contents/MacOS/EXPOSE"
message | "The executable does not have the hardened runtime enabled."
docUrl | null
architecture | "x86_64"
4 |  
severity | "warning"
code | null
path | "EXPOSE.zip/EXPOSE.app/Contents/MacOS/InstallTool.app/Contents/MacOS/InstallTool"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "x86_64"
5 |  
severity | "warning"
code | null
path | "EXPOSE.zip/EXPOSE.app/Contents/MacOS/InstallTool.app/Contents/MacOS/InstallTool"
message | "The executable does not have the hardened runtime enabled."
docUrl | null
architecture | "x86_64"
6 |  
severity | "warning"
code | null
path | "EXPOSE.zip/EXPOSE.app/Contents/Plugins/Event Kit.bundle/Contents/MacOS/Event Kit"
message | "The binary uses an SDK older than the 10.9 SDK."
docUrl | null
architecture | "x86_64"

**Comment by ArminDeeg** [comment]
OK got it, your sample is to sign the 4d.app only and not build apps/clients/servers

So I have to add the missing parts by myself :-)

But I get still one error, what is wrong ?


issues |  
-- | --
0 |  
severity | "warning"
code | null
path | "EXPOSE.zip/EXPOSE.app/Contents/MacOS/EXPOSE"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "x86_64"

code to sign inside your test method
		$componentPath:=$path+New collection("";"Contents";"MacOS";"").join(Folder separator)
		DOCUMENT LIST($componentPath;$componentPaths;Ignore invisible | Absolute path)
		For ($i;1;Size of array($componentPaths))
			If ($componentPaths{$i}#"Install@")
				$componentPath:=$componentPaths{$i}
				$statuses.push(codesign ($componentPath;$signingIdentity;$plist;$entitlements;$force))
			End if 
		End for

**Comment by miyako** [comment]
rather than the code itself, there might be useful information in the ``$status`` collection.

**Comment by ArminDeeg** [comment]
Got this in debugger:
![error](https://user-images.githubusercontent.com/6436037/67113385-a9c57c80-f1d9-11e9-8777-b2ac6ab4ebcd.png)

Got 2 more error entries:

![Bildschirmfoto 2019-10-18 um 19 02 58](https://user-images.githubusercontent.com/6436037/67113604-3c661b80-f1da-11e9-87b3-1f02a7adc427.png)

![Bildschirmfoto 2019-10-18 um 19 04 24](https://user-images.githubusercontent.com/6436037/67113615-41c36600-f1da-11e9-8bca-b944fd0525c1.png)

If you like to try it with my app: http://www.node.de/n.zip


Thanks Armin

**Comment by miyako** [comment]
you might want to Google the exact error message in quotes.

**Comment by ArminDeeg** [comment]
Hi Miyako,
yes I've found it and think that I have to suppress out the --deep option during codesign for this.

Sure I and other developers can adjust the tool with try and error until it fits. I thought, that I inform you about my problems to get an enhanced version which works maybe also as a drop in component to sign build apps clients and server.

perhaps also with the **xcrun stapler staple** option or the app

You have maybe tested only with the 4d.app and not with compiled build apps, or my xcode 10.1 on 10.13.6 is to old.

Thanks Armin

**Comment by ArminDeeg** [comment]
Miyako, I don't get it running with your build tool.

The app report successful notarized, but there are issues inside:

If you like to try it with my app: [](http://www.node.de/n.zip)
fresh build, but not signed

  |  
-- | --
logFormatVersion | 1
jobId | "b7c7aba2-2523-4c9f-a9dd-fee2141ce498"
status | "Accepted"
statusSummary | "Ready for distribution"
statusCode | 0
archiveFilename | "EXPOSE.zip"
uploadDate | "2019-10-21T12:07:00Z"
sha256 | "b69fdf6006ef330bf300736fa63b39dddeb4f532d8b9a19dce11a35feae54e1b"

ISSUES:


issues |  
-- | --
0 |  
severity | "warning"
code | null
path | "EXPOSE.zip/EXPOSE.app/Contents/MacOS/EXPOSE"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "x86_64"
1 |  
severity | "warning"
code | null
path | "EXPOSE.zip/EXPOSE.app/Contents/MacOS/InstallTool.app/Contents/MacOS/InstallTool"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "x86_64"

**Comment by ArminDeeg** [comment]
Tried to sign 4D v17r6 4D.APP (latest build 17 R6 build 17R6.243126) and got

223 warnings, here are the first 15, maybe 4D v17r6 works different than v17r5
But I need to sign and notarize my v17r6 build apps/client/servers

Armin

P.S.: modified your code only at 3 lines:
line 25: $path:="OSX_11:Users:armindeeg:Desktop:4D v17 R6:Test:4D.app:"
line 220: $params.username:="xxxxx"  //account
line 221: $params.password:="xxxxx"  //location for app specific password

issues |  
-- | --
0 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/MacOS/4D"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "x86_64"
1 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/M…tents/MacOS/InstallTool"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "x86_64"
2 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/M…tents/MacOS/InstallTool"
message | "The executable does not …rdened runtime enabled."
docUrl | null
architecture | "x86_64"
3 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…ces/php/Mac/php-fcgi-4d"
message | "The binary uses an SDK older than the 10.9 SDK."
docUrl | null
architecture | "x86_64"
4 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…es/DWARF/TRMosaicLayout"
message | "The binary is not signed."
docUrl | null
architecture | "i386"
5 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…es/DWARF/TRMosaicLayout"
message | "The signature does not include a secure timestamp."
docUrl | null
architecture | "i386"
6 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…es/DWARF/TRMosaicLayout"
message | "The binary is not signed."
docUrl | null
architecture | "x86_64"
7 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…es/DWARF/TRMosaicLayout"
message | "The signature does not include a secure timestamp."
docUrl | null
architecture | "x86_64"
8 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…es/DWARF/TRMosaicLayout"
message | "The binary is not signed."
docUrl | null
architecture | "x86_64h"
9 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…es/DWARF/TRMosaicLayout"
message | "The signature does not include a secure timestamp."
docUrl | null
architecture | "x86_64h"
10 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…ramework/TRMosaicLayout"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "i386"
11 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…ramework/TRMosaicLayout"
message | "The signature does not include a secure timestamp."
docUrl | null
architecture | "i386"
12 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…ramework/TRMosaicLayout"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "x86_64"
13 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…ramework/TRMosaicLayout"
message | "The signature does not include a secure timestamp."
docUrl | null
architecture | "x86_64"
14 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…tedCollectionViewLayout"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "i386"
15 |  
severity | "warning"
code | null
path | "4D.dmg/4D.app/Contents/R…tedCollectionViewLayout"
message | "The signature does not include a secure timestamp."
docUrl | null
architecture | "i386"

**Comment by ArminDeeg** [comment]
Miyako FYI,

I've tested the old build app utility from 20th june and this one works, no warnings except for an old plugin.
Something in the new version cause the warnings on the notarization result.

Armin

**Comment by miyako** [comment]
are you using the version newer than Oct. 8?
because there was a request from a user, to modify the code so that it does not throw "undefined" errors in compiled mode.
it was a bad idea, I reverted in Oct. 8.

**Comment by ArminDeeg** [comment]
Yes, I use the latest 7 days old version which shows the notarization warnings.

the old version from 20.6.2019 does not show these kind of warnings. If you like you can test it with my app, If posted a link top the n.zip some message before.

I've tested both the latest and the old from june in uncompiled mode

**Comment by miyako** [comment]
most of your warnings are about 4D for iOS, which should not exist in a typical final application.

also, earlier you mentioned about removing ``--deep``. 

if true, you are not using the component as it was designed.

**Comment by ArminDeeg** [comment]
no removing --deep had no effect
-------
I think, I've found it.

the last call before the **end if**
	  //the app 
	$statuses.push(codesign ($path;$signingIdentity;$plist;$entitlements**;$noOptions**))

When I remove the last parameter and step into the first **If (Count parameters>4)** inside the codesign method, then the codes produces no warnings from apple notarization. But there are some checks for the now missing parameter 5

![Bildschirmfoto 2019-10-21 um 17 44 47](https://user-images.githubusercontent.com/6436037/67220693-88a79a80-f42a-11e9-9cc8-b73cb978774c.png)

**Comment by miyako** [comment]
if there is a count parameters then it is not the latest version.
the whole point of the correction was to remove parameter counting.

**Comment by miyako** [comment]
I think the error originates from a wrong test path name 
```
$componentPath:=$path+New collection("";"Contents";"MacOS";"InstallTool.app";"").join(Folder separator)
If (Test path name($componentPath)=Is a folder)
$statuses.push(codesign ($componentPath;$signingIdentity;$plist;$entitlements;$force))
End if 
```

this was for a different user using the code for 17.x and 17 R (installer location is different)

**Comment by ArminDeeg** [comment]
Hi Miyako,

I thought I can get the latest version on this button ?

<img width="1029" alt="Bildschirmfoto 2019-10-21 um 22 58 47" src="https://user-images.githubusercontent.com/6436037/67242798-8ce9ad00-f456-11e9-9905-e9fbd87ce8f3.png">

And Codesign has the parameter counting:

<img width="661" alt="Bildschirmfoto 2019-10-21 um 22 58 21" src="https://user-images.githubusercontent.com/6436037/67242830-9bd05f80-f456-11e9-90f8-ee079609c28c.png">

**Comment by miyako** [comment]
the topmost ``Count parameters`` is OK. the problem was with the ones down below.
keep in mind that the ``TEST`` method is updated too.

with the latest version, can you not notarize without modification (other than account info.) ?

**Comment by ArminDeeg** [comment]
Thanks Miyako,

we get closer to a solution:

now I get this warnings: (Event Kit has to be updated from me)


s |  
-- | --
0 |  
severity | "warning"
code | null
path | "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/SQLServer.bundle/Contents/MacOS/SQLServer"
message | "The signature of the binary is invalid."
docUrl | null
architecture | "x86_64"
1 |  
severity | "warning"
code | null
path | "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/SQLServer.bundle/Contents/MacOS/SQLServer"
message | "The signature algorithm used is too weak."
docUrl | null
architecture | "x86_64"
2 |  
severity | "warning"
code | null
path | "EXPOSE.dmg/EXPOSE.app/Contents/Native Components/SQLServer.bundle/Contents/MacOS/SQLServer"
message | "The signature does not include a secure timestamp."
docUrl | null
architecture | "x86_64"
3 |  
severity | "warning"
code | null
path | "EXPOSE.dmg/EXPOSE.app/Contents/Plugins/Event Kit.bundle/Contents/MacOS/Event Kit"
message | "The binary uses an SDK older than the 10.9 SDK."
docUrl | null
architecture | "x86_64"

**Comment by ArminDeeg** [comment]
Changed on your test method is only
Account Info and path.

And now the altool method, does not return the ticket id inside $params like before.

**Comment by miyako** [comment]
the old code made a 2nd call immediately after uploading, but this could result in a success:false, because the call was too early.

so I removed 

```
If ($status.RequestUUID#Null)
$params.RequestUUID:=$status.RequestUUID
//2nd call, get status
$status:=altool ($params)
End if 
```

but I guess it was only necessary to remove the line

```
$status:=altool ($params)
```

**Comment by miyako** [comment]
I didn't reproduce the SQLServer issue.

https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma123/v4/d7/bd/b5/d7bdb5bd-2c89-b2e7-2c61-c8b659eca1ee/developer_log.json?accessKey=1571947244_7100595096977786776_FQRZIuEIF%2Fh4Cip4d6z7pFXZM9mBOLDonOCam435OTbP4g%2F0jjyZhUx4JdQt4hZCoHvNc6wf%2BtkZAw3iZuNwnyYWsT7HdLhWurhtmVCbEpoklG6tEAz9d1J%2B3dcq%2FGx8E5n3wgbk6IoVsdlAcXmhvleDjIcc1sPPGsOgpAYYh4g%3D

**Comment by ArminDeeg** [comment]
First I had the SQL Server issue, then the WebViewerSystem and then the CodeEditor

Don't know why, but I've added these 3 blocks to resolve it.

Now apple reports only the old event kit plugin, which is my next step.

Maybe it is my 10.13.6 with Xcode 10.1 ?

		  //sign with hardened runtime because this is an app
		$componentPath:=$path+New collection("";"Contents";"Native Components";"SQLServer.bundle";"Contents";"MacOS";"SQLServer").join(Folder separator)
		$statuses.push(codesign ($componentPath;$signingIdentity;$plist;$entitlements;$force))
		
		  //sign with hardened runtime because this is an app
		$componentPath:=$path+New collection("";"Contents";"Native Components";"WebViewerSystem.bundle";"Contents";"MacOS";"WebViewerSystem").join(Folder separator)
		$statuses.push(codesign ($componentPath;$signingIdentity;$plist;$entitlements;$force))
		
		  //sign with hardened runtime because this is an app
		$componentPath:=$path+New collection("";"Contents";"Native Components";"CodeEditor.bundle";"Contents";"MacOS";"CodeEditor").join(Folder separator)
		$statuses.push(codesign ($componentPath;$signingIdentity;$plist;$entitlements;$force))

**Comment by ArminDeeg** [comment]
Hi Miyako,

with xcode 10.3 it works fine on macOS 10.13.6
Here is a link how to install xcode 10.3 on High Sierra [https://codewithchris.com/xcode-update/
](https://codewithchris.com/xcode-update/
)

With xcode 10.1 I get some warnings. So I think minimum xcode with command line tools is 10.3

Thank for your support Armin

**Comment by miyako** [comment]
thanks for sharing!
