### ISSUE TITLE
Allow to select the team if account associated to multiple team #feature

### ISSUE THREAD

**Issue by phimage** [miyako/4d-utility-build-application#7]
From altool doc
```
--asc-provider <provider_shortname> Required with --notarize-app and --notarization-history when a user account is associated with multiple providers.
```

For instance
```4d
If (Value type($params.ascProvider)=Is text)
   $command:=$command+" --asc-provider"+$params.ascProvider
End if 
```

on github
https://github.com/search?q=--asc-provider&type=Code

**Comment by nilskoll** [comment]
I ran into the same need for adding --asc-provider as I got the following error when trying to notarize the app:

> Error: Your Apple ID account is attached to other iTunes providers. You will need to specify which provider you intend to submit content to by using the -itc_provider command. Please contact us if you have questions or need help. (1627)

The --asc-provider could be team name (was in my case with an enterprise account). In any case you can use the following command to get a provider listing:

/Applications/Xcode.app/Contents/Developer/usr/bin/iTMSTransporter -m provider -u "<apple-id>" -p "<password>"

Use the short name from the response.

**Comment by miyako** [comment]
thank you for the pointers. I tried the format `@keychain:{label}` it seems to be not supported by  **iTMSTransporter**. the app specific password had to be passed in plain text.

**Comment by miyako** [comment]
added `$params.ascProvider` to `altool`

`
