### ISSUE TITLE
TEST method won't run

### ISSUE THREAD

**Issue by scopie2** [miyako/4d-utility-build-application#9]
I had to move to Catalina because my old computer was failing and I got a new computer. I have used your Test method in the 4d-utility-build-application to sign my app many times — thank you — but now I get two errors. Both of the "not found" Folders referenced in the path error messages (below) are clearly present in the Contents Folder when I look there, spelled the same. Also puzzling is the "Native Components" Folder is in paths earlier in the code and seems to work OK there. In line 122, however, it's the final item in the path. Also, in lines 58-60 the same code is used but you check the path is valid so it doesn't generate an error but may not be signing the items in the folder. 

Any suggestions would be welcome. 

<img width="634" alt="Screen Shot 2020-01-01 at 11 42 52 AM" src="https://user-images.githubusercontent.com/47672751/71645419-1a365280-2c8d-11ea-972f-9c5eb1dc4bc7.png">

<img width="638" alt="Screen Shot 2020-01-01 at 11 44 37 AM" src="https://user-images.githubusercontent.com/47672751/71645421-24f0e780-2c8d-11ea-90b5-876871594f80.png">

**Comment by miyako** [comment]
just tested with 17.3 (245877) I don't reproduce **any** of the problems.

you are in a better position to check the file system locally:
if the path is really empty, you can skip it like in line 58.

**Comment by scopie2** [comment]
You are absolutely right. Somehow my $path variable got subtly changed and I didn't notice it until I checked 4 times. All is good now.

Thank You
